### ISSUE TITLE
some error windows python34

### ISSUE THREAD

**Issue by dr04** [osener/youtube2srt#2]
youtube2srt.py", line 95
    except (urllib2.URLError, urllib2.HTTPError, httplib.HTTPException), err:
                                                                       ^
SyntaxError: invalid syntax

**Comment by dr04** [comment]
I think I need install python27. I don't now how it's right with windows installed python34 =)

**Comment by ozanvos** [comment]
I'd never tested it with Python 3 before, thanks for the heads up. This should be fixed on master.
